theme: minima
title: Unsettled 😃
author: Teddy Waweru N.
email: teddywaweru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I hope this blog will be a clear distinction to my future self on how great it is to trust my process & to stick to a consistent momentum 
  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  www.github.com/teddywaweru # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
